title: Jekyll Test

collections:
  posts:
    output: true
    title: Blog Posts
    description: Various posts about the progression of GoStatic
    permalink: /posts/:path/
  authors:
    output: true
    title: Authors
    description: Directory of contributors to the site
    permalink: /authors/:path/

gostatic:
  build:
    command:
    - echo "Using Custom Command System\!"
    - jekyll build -v
    - jekyll build --trace --destination $SITE_DIR --config=_config.production.yml
